<?php

namespace ContainerGlSR84c;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFamille2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QvxxghZ.App\Entity\Famille' shared service.
     *
     * @return \App\Entity\Famille
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.QvxxghZ": it references class "App\\Entity\\Famille" but no such service exists.');
    }
}
