<?php

namespace ContainerV37Cn75;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XrHuo33Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XrHuo33' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XrHuo33'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Commande' => ['privates', '.errored..service_locator.XrHuo33.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.XrHuo33": it references class "App\\Entity\\Commande" but no such service exists.'],
            'cr' => ['privates', 'App\\Repository\\DetailCommandeRepository', 'getDetailCommandeRepositoryService', true],
        ], [
            'Commande' => 'App\\Entity\\Commande',
            'cr' => 'App\\Repository\\DetailCommandeRepository',
        ]);
    }
}
