<?php

namespace ContainerArAHeqL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2JPWHuuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2JPWHuu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2JPWHuu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Commande' => ['privates', '.errored..service_locator.2JPWHuu.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.2JPWHuu": it references class "App\\Entity\\Commande" but no such service exists.'],
            'CommandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'DetailCommandeRepository' => ['privates', 'App\\Repository\\DetailCommandeRepository', 'getDetailCommandeRepositoryService', true],
        ], [
            'Commande' => 'App\\Entity\\Commande',
            'CommandeRepository' => 'App\\Repository\\CommandeRepository',
            'DetailCommandeRepository' => 'App\\Repository\\DetailCommandeRepository',
        ]);
    }
}
