<?php

namespace ContainerXAWYRt6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommande5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._8F.4ml.App\Entity\Commande' shared service.
     *
     * @return \App\Entity\Commande
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._8F.4ml": it references class "App\\Entity\\Commande" but no such service exists.');
    }
}
