<?php

namespace ContainerR5bykjD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NVpfyTUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NVpfyTU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NVpfyTU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'detailCommande' => ['privates', '.errored..service_locator.NVpfyTU.App\\Entity\\DetailCommande', NULL, 'Cannot autowire service ".service_locator.NVpfyTU": it references class "App\\Entity\\DetailCommande" but no such service exists.'],
            'detailCommandeRepository' => ['privates', 'App\\Repository\\DetailCommandeRepository', 'getDetailCommandeRepositoryService', true],
        ], [
            'detailCommande' => 'App\\Entity\\DetailCommande',
            'detailCommandeRepository' => 'App\\Repository\\DetailCommandeRepository',
        ]);
    }
}
