<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commande extends \App\Entity\Commande implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'codeCommande', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'dateSouhaite', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'utilisateur', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'detailCommandes', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'commentaire'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'codeCommande', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'dateSouhaite', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'utilisateur', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'detailCommandes', '' . "\0" . 'App\\Entity\\Commande' . "\0" . 'commentaire'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Commande $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeCommande(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeCommande', []);

        return parent::getCodeCommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeCommande(string $codeCommande): \App\Entity\Commande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeCommande', [$codeCommande]);

        return parent::setCodeCommande($codeCommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\DateTimeInterface $date): \App\Entity\Commande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateSouhaite(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateSouhaite', []);

        return parent::getDateSouhaite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateSouhaite(\DateTimeInterface $dateSouhaite): \App\Entity\Commande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateSouhaite', [$dateSouhaite]);

        return parent::setDateSouhaite($dateSouhaite);
    }

    /**
     * {@inheritDoc}
     */
    public function isEtat(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEtat', []);

        return parent::isEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(bool $etat): \App\Entity\Commande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateur(): ?\App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateur', []);

        return parent::getUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilisateur(?\App\Entity\Utilisateur $utilisateur): \App\Entity\Commande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilisateur', [$utilisateur]);

        return parent::setUtilisateur($utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetailCommandes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetailCommandes', []);

        return parent::getDetailCommandes();
    }

    /**
     * {@inheritDoc}
     */
    public function addDetailCommande(\App\Entity\DetailCommande $detailCommande): \App\Entity\Commande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDetailCommande', [$detailCommande]);

        return parent::addDetailCommande($detailCommande);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDetailCommande(\App\Entity\DetailCommande $detailCommande): \App\Entity\Commande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDetailCommande', [$detailCommande]);

        return parent::removeDetailCommande($detailCommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', []);

        return parent::getCommentaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaire(string $commentaire): \App\Entity\Commande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaire', [$commentaire]);

        return parent::setCommentaire($commentaire);
    }

}
