<?php

namespace ContainerSsYfMUT;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CsEY2JIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CsEY2JI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CsEY2JI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Commande' => ['privates', '.errored..service_locator.CsEY2JI.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.CsEY2JI": it references class "App\\Entity\\Commande" but no such service exists.'],
            'CommandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
        ], [
            'Commande' => 'App\\Entity\\Commande',
            'CommandeRepository' => 'App\\Repository\\CommandeRepository',
        ]);
    }
}
