<?php

namespace ContainerEFM7W7v;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSousFamille2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tCjhayM.App\Entity\SousFamille' shared service.
     *
     * @return \App\Entity\SousFamille
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tCjhayM": it references class "App\\Entity\\SousFamille" but no such service exists.');
    }
}
