<?php

namespace ContainerXi3TGET;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IsRIZLmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IsRIZLm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IsRIZLm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UtilisateurController::delete' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController::edit' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController::index' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\UtilisateurController::new' => ['privates', '.service_locator.1RhB0LO', 'get_ServiceLocator_1RhB0LOService', true],
            'App\\Controller\\UtilisateurController::show' => ['privates', '.service_locator.r5W7ygF', 'get_ServiceLocator_R5W7ygFService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UtilisateurController:delete' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController:edit' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController:index' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\UtilisateurController:new' => ['privates', '.service_locator.1RhB0LO', 'get_ServiceLocator_1RhB0LOService', true],
            'App\\Controller\\UtilisateurController:show' => ['privates', '.service_locator.r5W7ygF', 'get_ServiceLocator_R5W7ygFService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UtilisateurController::delete' => '?',
            'App\\Controller\\UtilisateurController::edit' => '?',
            'App\\Controller\\UtilisateurController::index' => '?',
            'App\\Controller\\UtilisateurController::new' => '?',
            'App\\Controller\\UtilisateurController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UtilisateurController:delete' => '?',
            'App\\Controller\\UtilisateurController:edit' => '?',
            'App\\Controller\\UtilisateurController:index' => '?',
            'App\\Controller\\UtilisateurController:new' => '?',
            'App\\Controller\\UtilisateurController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
