<?php

namespace ContainerU6JtHaB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IA2o2s2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IA2o2s2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IA2o2s2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'classificationrepo' => ['privates', 'App\\Repository\\ClassificationRepository', 'getClassificationRepositoryService', true],
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'classificationrepo' => 'App\\Repository\\ClassificationRepository',
            'userPasswordHasher' => '?',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
