<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH8xHaUD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH8xHaUD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH8xHaUD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH8xHaUD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH8xHaUD\App_KernelDevDebugContainer([
    'container.build_hash' => 'H8xHaUD',
    'container.build_id' => '1f3b930a',
    'container.build_time' => 1674145198,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH8xHaUD');
