<?php

namespace ContainerJp0hBwb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P3K8PRyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p3K8PRy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p3K8PRy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'familleRepository' => ['privates', 'App\\Repository\\FamilleRepository', 'getFamilleRepositoryService', true],
            'twig' => ['privates', 'twig', 'getTwigService', false],
        ], [
            'familleRepository' => 'App\\Repository\\FamilleRepository',
            'twig' => '?',
        ]);
    }
}
