<?php

namespace ContainerJp0hBwb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UrG8SnNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UrG8SnN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UrG8SnN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Commande' => ['privates', '.errored..service_locator.UrG8SnN.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.UrG8SnN": it references class "App\\Entity\\Commande" but no such service exists.'],
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'cr' => ['privates', 'App\\Repository\\DetailCommandeRepository', 'getDetailCommandeRepositoryService', true],
        ], [
            'Commande' => 'App\\Entity\\Commande',
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
            'cr' => 'App\\Repository\\DetailCommandeRepository',
        ]);
    }
}
