<?php

namespace ContainerUnFOKf8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetailCommandeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NVpfyTU.App\Entity\DetailCommande' shared service.
     *
     * @return \App\Entity\DetailCommande
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NVpfyTU": it references class "App\\Entity\\DetailCommande" but no such service exists.');
    }
}
